# -*- coding: utf-8 -*-
"""19.02.2024.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qoAXoj020FDnFEcmcdMWfqLsUHDW2bQH

#1 Faça um programa que peça uma nota, entre zero e dez. Mostre uma mensagem caso o valor seja inválido e continue pedindo até que o usuario informe um valor valido
"""

nota = -1
while nota < 0 or nota > 10:
  nota = float(input("Informe uma nota entre zero e dez: "))
  if nota < 0 or nota > 10:
    print("Valor inválido, tente novamente")

"""#2 Faça um programa que calcule e mostre a média aritmética de N notas"""

stop = 1
soma = 0
contador = 0
while stop == 1:
  stop =int(input("Deseja inseriar uma nota [1]Sim [0]Não: "))
  if stop == 1:
    nota = float(input("Insira uma nota: "))
    soma += nota
    contador += 1
  elif stop == 0:
    print(f"A média das notas é: {soma / contador}")
  else:
    print("Valor inválido!")
    stop = 1

"""#3 Faça um programa que leia um nome de usuário e a sua senha e não aceite a senha igual ao nome de usuário, mostrando uma mensagem de erro e voltando a pedir as informações."""

verify = "false"
while verify == "false":
  usuario = str(input("Insira seu usuário: "))
  senha = str(input("Insira sua senha: "))
  if senha == usuario:
    print("Senha não pode ser igual ao usuario!")
    verify = "false"
  elif senha != usuario:
    verify = "true"
    print(f"Cadastro realizado com sucesso, seja bem vindo {usuario}!")

"""#4 Um funcionário de uma empresa recebe aumento salarial anualmente.
Sabe-se que: Esse funcionario foi contratado em 1995, co salario inicial de 1000; em 1996 recebeu aumento de 1,5% sobre seu salario inicial; a partir de 1997 (inclusive) os aumentos salariais sempre correspondem ao dobro do percentual do ano anterior. Faça um programa que determine o salario atual desse funcionario. Após concluir isto, altere o programa permitindo que o usuário digite o salario inicial do funcionário.
"""

salario = float(input("Insira o salário: "))
ano = 1995
percentual = 0.015
aumento = 0
while ano <= 2024:
  ano += 1
  aumento = salario * percentual
  salario += aumento
  percentual *= 2
  print(f"Ano: {ano}")
  print(f"Salário: {salario}")

"""#5 Faça um programa que leia e valide as seguintes informações:
*Nome: maior que tres caracteres
*Idade: entre 0 e 150
*Salario: maior que 0
Sexo: 'f' ou 'm'
Estado civil: 's', 'c', 'v', 'd'
"""

v_nome = "false"
v_idade = "false"
v_salario = "false"
v_sexo = "false"
v_estc = "false"

while v_nome == "false":
  nome = str(input("Insira seu nome: "))
  if len(nome) <= 3:
    print("Por favor, informe um nome acima de 3 caracteres.")
    v_nome = "false"
  else:
    v_nome = "true"

while v_idade == "false":
  idade = int(input("Insira sua idade: "))
  if idade < 0 or idade > 150:
    print("Por favor, informe uma idade entre 0 e 150.")
    v_idade = "false"
  else:
    v_idade = "true"

while v_salario == "false":
  salario = int(input("Insira seu salário: "))
  if salario <= 0:
    print("Por favor, informe um salário acima de 0.")
    v_salario = "false"
  else:
    v_salario = "true"

while v_sexo == "false":
  print("Insira seu sexo:")
  print("[f] Feminino")
  print("[m] Masculino")
  sexo = str(input())
  if sexo != "f" and sexo != "m":
    print("Valor inválido!")
    v_sexo = "false"
  else:
    v_sexo = "true"

while v_estc == "false":
  print("Insira seu estado civil: ")
  print("[s] Solteiro(a)")
  print("[c] Casado(a)")
  print("[v] Viúvo(a)")
  print("[d] Divorciado(a)")
  estc = str(input())
  if estc != "s" and estc != "c" and estc != "v" and estc != "d":
    print("Valor inválido!")
    v_estc = "false"
  else:
    v_estc = "true"

print("Cadastrado com sucesso!")
print(f"Nome: {nome}")
print(f"Idade: {idade}")
print(f"Salário: {salario}")
print(f"Sexo: {sexo}")
print(f"Estado Civil:{estc}")

"""#6 Supondo que a população de um país A seja da ordem de 80000 habitantes com uma taxa anual de crescimento de 3% e que a população de B seja 200000 habitantes com uma taxa de crescimento de 1.5%. Faça um programa que calcule e escreva o número de anos necessários para quea população do país A ultrapasse ou iguale a população do país  B, mantidas as taxas de crescimento."""

populacao_a = 80000
crescimento_a = 0.03
populacao_b = 200000
crescimento_b = 0.015
anos = 0

while populacao_a < populacao_b:
  anos += 1
  populacao_a += populacao_a * crescimento_a
  populacao_b += populacao_b * crescimento_b
  print(f" Ano {anos}: população A: {populacao_a}")
  print(f" Ano {anos}: população B: {populacao_b}")

print(f"Levariam {anos} anos para que a população do país A ultrapasse o país B!")

"""#7 Faça um programa que calcule o fatorial de um número inteiro fornecido pelo usuário. Ex 5! = 5.4.3.2.1 = 120"""

numero = int(input("Informe um número:"))
resultado = numero
while numero >= 2:
  numero -= 1
  resultado *= numero
print(f"O resultado fatorial é: {resultado}")

"""#8 Faça um programa que solicite ao usuário números indefinidamente até que ele digite 0. Em seguida, o programa deve imprimir a m~edia dos números digitados."""

numero = 1
soma = 0
contador = 0
while numero != 0:
  numero = int(input("Insira um número: "))
  soma += numero
  contador += 1
print (f"a média dos números digitados é: { soma / contador}")

"""#9 A série de fibonacci é formada pela sequência 1,1,2,3,5,8,13,21,34,55,... Faça um programa capaz de gerar a série até o n-ésimo termo."""

termo = int(input("informe o termo que deseja da sequencia de fibonacci: "))
termo -= 2
contador = 0
t1 = 1
t2 = 1
t3 = 2
print(t1)
print(t2)
while contador != termo:
  t3 = t2 + t1
  t1 = t2
  t2 = t3
  contador += 1
  print(t3)

"""#10 O Sr. Manoel Joaquim expandiu seus negócios para além dos negócios de 1,99 e
agora possui uma loja de conveniências. Faça um programa que implemente uma
caixa registradora rudimentar.
 O programa deverá receber um número desconhecido de valores referentes
aos preços das mercadorias. Um valor zero deve ser informado pelo
operador para indicar o final da compra.
 O programa deve então mostrar o total da compra e perguntar o valor em
dinheiro que o cliente forneceu, para então calcular e mostrar o valor do
troco. Após esta operação, o programa deverá voltar ao ponto inicial, para
registrar a próxima compra.
 A saída deve ser conforme o exemplo abaixo:
 Lojas Tabajara
 Produto 1: R$ 2.20
 Produto 2: R$ 5.80
 Produto 3: R$ 0
 Total: R$ 9.00
 Dinheiro: R$ 20.00
 Troco: R$ 11.00

"""

soma = 0
contador = 0
finalizar = "n"
pagamento = 0
entrada = 1
while finalizar == "n":
  soma = 0
  contador = 0
  finalizar = "n"
  pagamento = 0
  entrada = 1
  while entrada != 0:
    contador += 1
    entrada = float(input("Insira um valor do produto ou 0 para finalizar a compra: "))
    soma += entrada
    print (f"Produto {contador}: R${entrada}")

  while pagamento < soma:
    pagamento = float(input("Insira o valor do pagamento: "))
    if pagamento == soma:
      print("Não é necessário troco.")
    elif pagamento > soma:
      print(f"Deve devolver em troco o valor de R${pagamento - soma}")
    elif pagamento < soma:
      print(f"O cliente falta pagar R${soma- pagamento}")
  print("Obrigado pela compra!")
  finalizar = str(input("Deseja finalizar o sistema [s] ou [n]: "))

"""#11 O cardápio de uma lanchonete é o seguinte:
Especificação Código Preço
 Cachorro Quente 100 R$ 1,20
 Bauru Simples 101 R$ 1,30
 Bauru com ovo 102 R$ 1,50
 Hambúrguer 103 R$ 1,20
 Cheeseburguer 104 R$ 1,30
 Refrigerante 105 R$ 1,00
Faça um programa que leia o código dos itens pedidos e as quantidades desejadas.
Calcule e mostre o valor a ser pago por item (preço * quantidade) e o total geral do
pedido. Considere que o cliente deve informar quando o pedido deve ser encerrado.
"""

pedido = "n"
valor_100 = 0
valor_101 = 0
valor_102 = 0
valor_103 = 0
valor_104 = 0
valor_105 = 0
q_100 = 0
q_101 = 0
q_102 = 0
q_103 = 0
q_104 = 0
q_105 = 0
while pedido == "n":
  print("Lanchonete Byte!")
  print("-------CARDAPIO-------")
  print("Cachorro quente [100] : R$1,20")
  print("Bauru Simples [101]: R$1,30")
  print("Bauru com Ovo [102]: R$1,50")
  print("Hambúrguer [103]: R$1,20")
  print("Cheeseburguer [104]: R$1,30")
  print("Refrigerante [105]: R$1,00")

  entrada = int(input("Insira o código do produto: "))
  if entrada == 100:
    q_100 = int(input("Cachorro Quente! Informe a quantidade: "))
    valor_100 = q_100 * 1.2
  elif entrada == 101:
    q_101 = int(input("Bauru Simples! Informe a quantidade: "))
    valor_101 = q_101 * 1.3
  elif entrada == 102:
    q_102 = int(input("Bauru com Ovo! Informe a quantidade: "))
    valor_102 = q_102 * 1.5
  elif entrada == 103:
    q_103 = int(input("Hambúrguer! Informe a quantidade: "))
    valor_103 = q_103 * 1.2
  elif entrada == 104:
    q_104 = int(input("Cheeseburguer! Informe a quantidade: "))
    valor_104 = q_104 * 1.3
  elif entrada == 105:
    q_105 = int(input("Refrigerante! Informe a quantidade: "))
    valor_105 = q_105 * 1
  pedido = str(input("Deseja finalizar o pedido: [s] ou [n]"))

print("Seu pedido foi:")
print(f"Cachorro Quente: R${valor_100}({q_100} X R$1,20)")
print(f"Bauru Simples: R${valor_101}({q_101} X R$1,30)")
print(f"Bauru com Ovo: R${valor_102}({q_102} X R$1,50)")
print(f"Hambúrguer: R${valor_103}({q_103} X R$1,20)")
print(f"Cheeseburguer: R${valor_104}({q_104} X R$1,30)")
print(f"Refrigerante: R${valor_105}({q_105} X R$1,00)")
print(f"TOTAL DO PEDIDO: R${valor_100 + valor_101 + valor_102+ valor_103+ valor_104+ valor_105}")

"""#12 Em uma eleição presidencial existem quatro candidatos. Os votos são informados por meio de código.
Os códigos são:
1,2,3,4 - candidatos
(montar tabela exempro -1 jose, -2 joao)
5 voto nulo
6 voto em branco

Faça um programa que calcule e mostre:
O total de votos para cada candidato
O total de votos nulos
O total de votos em branco
A percentagem de votos nulos sobre o total de votos
A percentagem de votos em branco sobre o total de votos
"""

fim = "n"
prisilhinha = 0
dentucinha = 0
arthur = 0
ana = 0
nulo = 0
branco = 0
while fim == "n":
  print("Eleições: Vote em seu futuro!")
  print("[1] Prisilhinha")
  print("[2] Dentucinha")
  print("[3] Arthur")
  print("[4] Ana")
  print("[5] Voto Nulo")
  print("[6] Voto Branco")
  voto = int(input("Informe seu voto: "))

  if voto == 1:
    prisilhinha += 1
  elif voto == 2:
    dentucinha += 1
  elif voto == 3:
    arthur += 1
  elif voto == 4:
    ana += 1
  elif voto == 5:
    nulo += 1
  elif voto == 6:
    branco += 1
  else:
    print("Valor inválido!")
  fim = str(input("deseja encerrar a votação: [s] ou [n]"))

print(f"Prisilhinha teve {prisilhinha} votos.")
print(f"Dentucinha teve {dentucinha} votos.")
print(f"Arthur teve {arthur} votos.")
print(f"Ana teve {ana} votos.")
print(f"O total de votos nulos foi de: {nulo}")
print(f"O total de votos brancos foi de: {branco}")
print(f"O percentual de votos nulos foi de: {(nulo * 100) / (prisilhinha + dentucinha + arthur + ana + nulo + branco)}")
print(f"O percentual de votos brancos foi de: {(branco * 100) / (prisilhinha + dentucinha + arthur + ana + nulo + branco)}")