# -*- coding: utf-8 -*-
"""23.02.2024-02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12RgC6sso20nxmoCjQ92JgpSchmjNpsGD
"""

palavra = str(input("Insira uma palavra: "))
#palavra_inversa = palavra[::-1]
palavra_inversa = ""
posicao = len(palavra) -1
for i in range(len(palavra)):
  palavra_inversa += palavra[posicao]
  posicao -= 1

if palavra == palavra_inversa:
  print(f"A palavra {palavra} é um palíndromo.")
else:
  print(f"A palavra {palavra} não é um palíndromo.")

num = -1
horizontal = ""
vertical = ""
while num < 0:
  num = int(input("Informe um número inteiro positivo: "))

horizontal += " "
for i in range(num):
  horizontal += "-"
horizontal += " "
print(horizontal)
vertical += ":"
for i in range(num):
  vertical += " "
vertical+= ":"
for i in range(num):
  print(vertical)
print(horizontal)

num = int(input("Informe um número inteiro positivo: "))
sinal = ""
for i in range(num):
  sinal += "+"
  print(sinal)